name: Deploy React/Vite Project to Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Checkout Code
      uses: actions/checkout@v4
    
    - name: 2. Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        # ❌ Yeh caching lines hata di hain taaki lock file error na aaye.
        # cache: 'npm' 
    
    - name: 3. Install Dependencies
      # npm ci ki jagah wapas npm install use kiya, taaki bina lock file ke kaam ho jaye.
      run: npm install 
    
    - name: 4. Build Project
      run: npm run build
    
    - name: 5. Upload Artifact
      # Latest stable action
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    
    steps:
    - name: 6. Deploy to GitHub Pages
      id: deployment
      # Latest stable action
      uses: actions/deploy-pages@v5
      
